name: Commit Logger

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Permet activació manual
  schedule:
    - cron: "59 23 * * 5" # Cada divendres a les 23:59 (UTC)

jobs:
  log-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 3 # Només baixa els últims 3 commits per eficiència

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20" # Versió de Go

      - name: Run commit logger script
        run: |
          cd scripts
          go run log_commits.go

      - name: Commit and push if changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add log/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto: Add latest commits log"
          git push
